create table "public"."category" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."category" enable row level security;

create table "public"."zone" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."zone" enable row level security;

alter table "public"."operator" add column "category_id" uuid not null;

alter table "public"."operator" add column "zone_id" bigint not null;

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (id);

CREATE UNIQUE INDEX zone_pkey ON public.zone USING btree (id);

alter table "public"."category" add constraint "category_pkey" PRIMARY KEY using index "category_pkey";

alter table "public"."zone" add constraint "zone_pkey" PRIMARY KEY using index "zone_pkey";

alter table "public"."operator" add constraint "operator_category_id_fkey" FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE not valid;

alter table "public"."operator" validate constraint "operator_category_id_fkey";

alter table "public"."operator" add constraint "operator_zone_id_fkey" FOREIGN KEY (zone_id) REFERENCES zone(id) ON DELETE CASCADE not valid;

alter table "public"."operator" validate constraint "operator_zone_id_fkey";

grant delete on table "public"."category" to "anon";

grant insert on table "public"."category" to "anon";

grant references on table "public"."category" to "anon";

grant select on table "public"."category" to "anon";

grant trigger on table "public"."category" to "anon";

grant truncate on table "public"."category" to "anon";

grant update on table "public"."category" to "anon";

grant delete on table "public"."category" to "authenticated";

grant insert on table "public"."category" to "authenticated";

grant references on table "public"."category" to "authenticated";

grant select on table "public"."category" to "authenticated";

grant trigger on table "public"."category" to "authenticated";

grant truncate on table "public"."category" to "authenticated";

grant update on table "public"."category" to "authenticated";

grant delete on table "public"."category" to "service_role";

grant insert on table "public"."category" to "service_role";

grant references on table "public"."category" to "service_role";

grant select on table "public"."category" to "service_role";

grant trigger on table "public"."category" to "service_role";

grant truncate on table "public"."category" to "service_role";

grant update on table "public"."category" to "service_role";

grant delete on table "public"."zone" to "anon";

grant insert on table "public"."zone" to "anon";

grant references on table "public"."zone" to "anon";

grant select on table "public"."zone" to "anon";

grant trigger on table "public"."zone" to "anon";

grant truncate on table "public"."zone" to "anon";

grant update on table "public"."zone" to "anon";

grant delete on table "public"."zone" to "authenticated";

grant insert on table "public"."zone" to "authenticated";

grant references on table "public"."zone" to "authenticated";

grant select on table "public"."zone" to "authenticated";

grant trigger on table "public"."zone" to "authenticated";

grant truncate on table "public"."zone" to "authenticated";

grant update on table "public"."zone" to "authenticated";

grant delete on table "public"."zone" to "service_role";

grant insert on table "public"."zone" to "service_role";

grant references on table "public"."zone" to "service_role";

grant select on table "public"."zone" to "service_role";

grant trigger on table "public"."zone" to "service_role";

grant truncate on table "public"."zone" to "service_role";

grant update on table "public"."zone" to "service_role";


